### PR TITLE
Added series updated endpoint.

### PR DESCRIPTION
**Pull request by mattkranzler5**

### CODE REVIEW

**Comment by UweTrottmann** [comment]
Thanks, I will look at this next week.

 

Uwe Trottmann

uwetrottmann.com

**Comment by mattkranzler5** [comment]
Also added the series actors endpoint & fixed a potential crash.

**Comment by UweTrottmann** [comment]
Thanks for the additions. And sorry, looks like it will be next week...

**Comment by UweTrottmann** [comment]
Alright, looks like the only thing missing are test cases:
- new test cases for each new endpoint
- adjusting the existing episode test to one with a double DVD number.

I do not have time right now, but I will add them eventually if you do not until then.

**Comment by UweTrottmann** [comment]
Alright, finally could make time to add tests. Will be released with `1.4.0`.

**Pull request merged**
